import type { Metadata } from '../api/schema'
import { Modal } from './Modal'
export function Methodology({ meta, close }: { meta?: Metadata; close: () => void }) {
  return <Modal title="Context, with its limits." close={close}><div className="methodology-body">
    <p className="modal-lede">SatBurn is a retrospective thermal-observation desk. Every marker is a starting point for human review, not a claim about what caused a fire.</p>
    <section><span>01</span><div><h3>Proxy categories, not verified causes</h3><p>Industrial candidates and wildfire candidates come from rule-based weak-label context. OSM proximity and land cover generate these categories. Unknown remains unknown. No classifier is operational, and no model probability is displayed.</p></div></section>
    <section><span>02</span><div><h3>A review score, not a severity forecast</h3><p>The API supplies a fixed 0–100 score using FRP, persistence, sensor confidence and night observations. It is not a probability, severity measurement, verified cause or dispatch recommendation. A low score does not establish safety. Marker rings encode review bands, not physical fire intensity.</p></div></section>
    <section><span>03</span><div><h3>Geographic evidence is incomplete</h3><p>OSM mapping is uneven; an absent facility is not proof that no industry exists. WorldCover 2021 v200 supplies static land-cover context for 2026 observations. Land cover may have changed. FIRMS detections have coarse geolocation and are not fire perimeters. The approximately 390 m footprint and 0.01° persistence grid are approximations.</p></div></section>
    <section><span>04</span><div><h3>Retrospective, local and bounded</h3><p>Persistence counts distinct acquisition dates in the inclusive trailing 30-calendar-day window; multiple same-day observations count once. It can include later observations on the acquisition date. Daily alert groups are spatial summaries, not incident boundaries. The queue sends no alerts.</p><p>This frontend uses the local Stage 6 snapshot only. There is no live FIRMS ingestion, external runtime data service, VNF matching or model serving.</p></div></section>
    <section><span>05</span><div><h3>Read the globe as a reference</h3><p>Natural Earth 1:110m outlines are bundled locally as visual reference, not precise facility or administrative boundaries. Markers retain API coordinates. Coincident observations overlap; use the observation index to inspect each one. The global snapshot summary and review queue remain unfiltered; filters apply to the globe and index.</p></div></section>
    {meta && <div className="api-limitations"><h3>Limitations returned by the API</h3><ul>{meta.limitations.map(text => <li key={text}>{text}</li>)}</ul><p>{meta.data_disclaimer}</p></div>}
  </div></Modal>
}
