import { ThermalTarget, QuickStats } from './types';

export const INITIAL_QUICK_STATS: QuickStats = {
  activeTargets: 14,
  industrialFlares: 8,
  unverifiedAnomalies: 3,
  criticalAlarms: 3,
};

export const MOCK_THERMAL_TARGETS: ThermalTarget[] = [
  {
    id: "TRG-JAM-01",
    name: "Jamnagar Petroleum Refinery Complex",
    facilityType: "Petrochemical & Crude Oil Processing",
    state: "Gujarat",
    coordinates: [22.4707, 70.0577],
    type: "PERSISTENT_FLARE",
    classification: "CONFIRMED INDUSTRIAL FLARE",
    sensorId: "VIIRS_VNP14IMGTDL",
    brightnessTempK: 512.4,
    brightTi4: 512.4,
    brightTi5: 340.2,
    brightTempC: 239.3,
    frpMW: 185.4,
    confidence: 99,
    osmOverlap: true,
    lastDetected: "2026-09-11 23:45:12 UTC",
    status: "VERIFIED_STABLE",
    defensePriority: "DELTA-1",
    riskScore: 88,
    isSynthetic: true,
    dataSourceLabel: "ORBITAL CACHE // VIIRS-SNPP REPLAY",
    description: "World's largest oil refinery complex. Continuous high-volume hydrocracker and coker flaring signature monitored across 365-day satellite baseline.",
    history7Days: [
      { date: "09-05", tempK: 508, frpMW: 180, isMockHistory: true },
      { date: "09-06", tempK: 510, frpMW: 182, isMockHistory: true },
      { date: "09-07", tempK: 514, frpMW: 188, isMockHistory: true },
      { date: "09-08", tempK: 511, frpMW: 184, isMockHistory: true },
      { date: "09-09", tempK: 513, frpMW: 186, isMockHistory: true },
      { date: "09-10", tempK: 512, frpMW: 185, isMockHistory: true },
      { date: "09-11", tempK: 512.4, frpMW: 185.4, isMockHistory: true },
    ]
  },
  {
    id: "TRG-BHI-02",
    name: "Bhilai Integrated Steel Plant",
    facilityType: "Metallurgical & Blast Furnace",
    state: "Chhattisgarh",
    coordinates: [21.1938, 81.3509],
    type: "PERSISTENT_FLARE",
    classification: "PERSISTENT BLAST FURNACE SIGNATURE",
    sensorId: "VIIRS_VNP14IMGTDL",
    brightnessTempK: 488.7,
    brightTi4: 488.7,
    brightTi5: 332.1,
    brightTempC: 215.6,
    frpMW: 142.1,
    confidence: 96,
    osmOverlap: true,
    lastDetected: "2026-09-11 23:30:04 UTC",
    status: "VERIFIED_STABLE",
    defensePriority: "BRAVO-1",
    riskScore: 78,
    isSynthetic: true,
    dataSourceLabel: "ORBITAL CACHE // VIIRS-SNPP REPLAY",
    description: "Major primary rail and heavy steel producer. Continuous thermal emissions originating from coke oven batteries and converter vessels.",
    history7Days: [
      { date: "09-05", tempK: 482, frpMW: 138, isMockHistory: true },
      { date: "09-06", tempK: 485, frpMW: 140, isMockHistory: true },
      { date: "09-07", tempK: 486, frpMW: 141, isMockHistory: true },
      { date: "09-08", tempK: 490, frpMW: 145, isMockHistory: true },
      { date: "09-09", tempK: 487, frpMW: 141, isMockHistory: true },
      { date: "09-10", tempK: 488, frpMW: 142, isMockHistory: true },
      { date: "09-11", tempK: 488.7, frpMW: 142.1, isMockHistory: true },
    ]
  },
  {
    id: "TRG-PAN-03",
    name: "Panipat Petrochemical Complex",
    facilityType: "Naphtha Cracker & Chemical Refinery",
    state: "Haryana",
    coordinates: [29.3909, 76.9637],
    type: "CRITICAL_SPIKE",
    classification: "ABNORMAL REFINERY SPIKE (+42%)",
    sensorId: "VIIRS_VNP14IMGTDL",
    brightnessTempK: 564.8,
    brightTi4: 564.8,
    brightTi5: 365.4,
    brightTempC: 291.7,
    frpMW: 342.6,
    confidence: 98,
    osmOverlap: true,
    lastDetected: "2026-09-11 23:51:30 UTC",
    status: "ACTIVE_ALERT",
    defensePriority: "DELTA-1",
    riskScore: 97,
    isSynthetic: true,
    dataSourceLabel: "ORBITAL CACHE // VIIRS-SNPP REPLAY",
    description: "CRITICAL ANOMALY: Thermal intensity spiked by +42% above 90-day baseline in olefin cracker zone. Immediate drone recon recommended.",
    history7Days: [
      { date: "09-05", tempK: 420, frpMW: 120, isMockHistory: true },
      { date: "09-06", tempK: 422, frpMW: 122, isMockHistory: true },
      { date: "09-07", tempK: 418, frpMW: 119, isMockHistory: true },
      { date: "09-08", tempK: 425, frpMW: 126, isMockHistory: true },
      { date: "09-09", tempK: 440, frpMW: 160, isMockHistory: true },
      { date: "09-10", tempK: 510, frpMW: 260, isMockHistory: true },
      { date: "09-11", tempK: 564.8, frpMW: 342.6, isMockHistory: true },
    ]
  },
  {
    id: "TRG-BAN-04",
    name: "Bandhavgarh Tiger Reserve Forest Corridor",
    facilityType: "Protected Dense Canopy Forestry",
    state: "Madhya Pradesh",
    coordinates: [23.7019, 81.0252],
    type: "BIOMASS_FIRE",
    classification: "NATURAL BIOMASS WILDFIRE",
    sensorId: "MODIS_MYD14",
    brightnessTempK: 395.2,
    brightTi4: 395.2,
    brightTi5: 308.1,
    brightTempC: 122.1,
    frpMW: 88.3,
    confidence: 94,
    osmOverlap: false,
    lastDetected: "2026-09-11 22:15:00 UTC",
    status: "UNDER_RECON",
    defensePriority: "ALPHA-2",
    riskScore: 65,
    isSynthetic: true,
    dataSourceLabel: "ORBITAL CACHE // VIIRS-SNPP REPLAY",
    description: "Rapidly spreading canopy surface fire detected across 1.4 km front line. Zero OSM industrial footprint detected. Forest department dispatched.",
    history7Days: [
      { date: "09-05", tempK: 300, frpMW: 2, isMockHistory: true },
      { date: "09-06", tempK: 302, frpMW: 3, isMockHistory: true },
      { date: "09-07", tempK: 305, frpMW: 5, isMockHistory: true },
      { date: "09-08", tempK: 310, frpMW: 12, isMockHistory: true },
      { date: "09-09", tempK: 345, frpMW: 45, isMockHistory: true },
      { date: "09-10", tempK: 380, frpMW: 72, isMockHistory: true },
      { date: "09-11", tempK: 395.2, frpMW: 88.3, isMockHistory: true },
    ]
  },
  {
    id: "TRG-PUN-05",
    name: "Punjab Agricultural Belt (Sangrur District)",
    facilityType: "Agro-Paddy Crop Residue Zone",
    state: "Punjab",
    coordinates: [30.2458, 75.8421],
    type: "AGRICULTURAL_STUBBLE",
    classification: "UNVERIFIED STUBBLE BURNING CLUSTER",
    sensorId: "SLSTR_SENTINEL3",
    brightnessTempK: 362.1,
    brightTi4: 362.1,
    brightTi5: 301.0,
    brightTempC: 89.0,
    frpMW: 34.5,
    confidence: 78,
    osmOverlap: false,
    lastDetected: "2026-09-11 21:05:44 UTC",
    status: "UNVERIFIED",
    defensePriority: "CHARLIE-3",
    riskScore: 42,
    isSynthetic: true,
    dataSourceLabel: "ORBITAL CACHE // VIIRS-SNPP REPLAY",
    description: "Low-temperature thermal cluster scattered over farm parcels. Signature aligns with seasonal post-harvest paddy residue open burning.",
    history7Days: [
      { date: "09-05", tempK: 315, frpMW: 10, isMockHistory: true },
      { date: "09-06", tempK: 320, frpMW: 12, isMockHistory: true },
      { date: "09-07", tempK: 330, frpMW: 18, isMockHistory: true },
      { date: "09-08", tempK: 345, frpMW: 24, isMockHistory: true },
      { date: "09-09", tempK: 350, frpMW: 28, isMockHistory: true },
      { date: "09-10", tempK: 358, frpMW: 31, isMockHistory: true },
      { date: "09-11", tempK: 362.1, frpMW: 34.5, isMockHistory: true },
    ]
  }
];
