import { test, expect } from '@playwright/test'
test('real snapshot: globe, filters, evidence, queue, local-only requests and offline recovery', async ({ page, context, request }, testInfo) => {
  const external: string[] = [], apiRequests: string[] = [], consoleErrors: string[] = []
  await context.route('**/*', route => {
    const url = new URL(route.request().url())
    if (!['http://127.0.0.1:5173', 'http://127.0.0.1:8000'].includes(url.origin)) { external.push(url.href); return route.abort() }
    if (url.origin.endsWith(':8000')) apiRequests.push(url.pathname + url.search)
    return route.continue()
  })
  page.on('pageerror', error => consoleErrors.push(error.message))
  const stats = await (await request.get('http://127.0.0.1:8000/api/v1/stats')).json()
  const alerts = await (await request.get('http://127.0.0.1:8000/api/v1/alerts')).json()
  await page.goto('/')
  await expect(page.getByText('Local API connected', { exact: true })).toBeVisible()
  await expect(page).toHaveTitle(/SatBurn/)
  const canvas = page.locator('canvas[data-globe-ready=true]')
  await expect(canvas).toBeVisible()
  await expect(canvas).toHaveAttribute('data-rendered-hotspots', String(stats.total_hotspots))
  await expect(page.getByText(stats.total_hotspots + ' observations', { exact: true })).toBeVisible()
  await expect(page.locator('.summary-card').first()).toContainText(String(stats.total_hotspots))
  await page.waitForTimeout(1800)
  await page.screenshot({ path: testInfo.outputPath('desktop-globe.png'), fullPage: true })
  await page.getByRole('button', { name: 'Focus region', exact: true }).click()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: testInfo.outputPath('region-globe.png'), fullPage: true })
  await page.getByRole('button', { name: 'Reset globe view' }).click()
  await page.getByRole('button', { name: /Inspect observation/ }).first().click()
  await expect(page.getByText('Evidence behind the score')).toBeVisible()
  await expect(page.getByText('Deterministic score · not a probability')).toBeVisible()
  await page.getByRole('button', { name: 'Methodology', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText(/WorldCover 2021 v200/)).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Methodology', exact: true })).toBeFocused()
  await page.getByLabel('Context category').selectOption('wildfire')
  await page.getByRole('button', { name: /Apply filters/ }).click()
  await expect(canvas).toHaveAttribute('data-rendered-hotspots', String(stats.class_counts.wildfire))
  await page.getByRole('button', { name: /High-priority review/ }).click()
  await expect(page.getByRole('button', { name: /Review alert / })).toHaveCount(stats.high_priority_alert_count)
  await page.getByRole('button', { name: /Daily groups/ }).click()
  await expect(page.locator('.group-item')).toHaveCount(stats.alert_group_count)
  await page.getByRole('button', { name: /Observations/ }).filter({ hasText: String(stats.high_priority_alert_count) }).click()
  await page.getByRole('button', { name: 'Review alert ' + alerts.items[0].hotspot_id, exact: true }).click()
  await expect(canvas).toHaveAttribute('data-rendered-hotspots', String(stats.total_hotspots))
  await expect(page.locator('.id-block')).toContainText(alerts.items[0].hotspot_id)
  await page.getByLabel('Minimum FRP', { exact: true }).fill('100000')
  await page.getByRole('button', { name: /Apply filters/ }).click()
  await expect(page.getByText('No matching observations')).toBeVisible()
  await expect(canvas).toHaveAttribute('data-rendered-hotspots', '0')
  await page.locator('.empty-state').getByRole('button', { name: 'Reset filters' }).click()
  await expect(canvas).toHaveAttribute('data-rendered-hotspots', String(stats.total_hotspots))
  await page.setViewportSize({ width: 834, height: 1112 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.waitForTimeout(500)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('tablet-globe.png'), fullPage: true })
  await context.route('http://127.0.0.1:8000/**', route => route.abort('connectionrefused'))
  // The periodic health request must detect a stopped backend without user interaction.
  await expect(page.getByText('The observation desk is offline.')).toBeVisible({ timeout: 25000 })
  await expect(page.locator('.summary-card')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('offline-state.png'), fullPage: true })
  await context.unroute('http://127.0.0.1:8000/**')
  await page.getByRole('button', { name: /Reconnect to local API/ }).click()
  await expect(page.getByText('Local API connected', { exact: true })).toBeVisible()
  for (const endpoint of ['health','meta','stats','hotspots','hotspots.geojson','alerts','alert-groups','risk-distribution']) {
    expect(apiRequests.some(url => url.startsWith('/api/v1/' + endpoint))).toBe(true)
  }
  expect(apiRequests.some(url => /offset=500/.test(url))).toBe(true)
  expect(apiRequests.some(url => /predicted_class=wildfire/.test(url))).toBe(true)
  expect(apiRequests.some(url => /\/hotspots\/[0-9a-f]{64}$/.test(url))).toBe(true)
  expect(external).toEqual([])
  expect(consoleErrors).toEqual([])
  await testInfo.attach('network-audit', { body: JSON.stringify({ apiRequests, external, consoleErrors }, null, 2), contentType: 'application/json' })
})
